Play travis
Otus-DevOps-2021-08/zmd73_infra pull request #1
Opened 2021-09-20 12:00 UTC by zmd73

2021-09-21 08:08 UTC, mrgreyves requested changes
Здравствуйте!) Проверил ваше дз.
Нужно добавлять описание к вашим пуллреквестам
![image](https://user-images.githubusercontent.com/34331259/134135278-bd05de4d-494a-4eb7-b94f-338270c36765.png)
Так же не хватает тестов, стоит свериться с методичкой, дз возвращаю на доработку.

2021-09-22 08:55 UTC, zmd73 commented
> 
> 
> Здравствуйте!) Проверил ваше дз.
> Нужно добавлять описание к вашим пуллреквестам
> ![image](https://user-images.githubusercontent.com/34331259/134135278-bd05de4d-494a-4eb7-b94f-338270c36765.png)
> Так же не хватает тестов, стоит свериться с методичкой, дз возвращаю на доработку.

Я бы сверился с методичкой но она уже не доступна...

2021-09-23 09:13 UTC, mrgreyves commented
Здравствуйте!) В смысли не доступна? Я пока что не буду двигать вашу карточку с домашкой, по ней все так же есть вопросы

2021-09-23 09:31 UTC, mrgreyves commented
![image](https://user-images.githubusercontent.com/34331259/134484567-0794ad56-3b99-42d0-b3e4-3fa8c0ea6f27.png)
Сейчас добавлен только auto-assign, хотя должны так же быть добавлены еще и тесты
То есть суммарно, должно выглядеть вот так
![image](https://user-images.githubusercontent.com/34331259/134484700-97b4926f-4b67-4b41-9ea0-a2515d41f0ce.png)
В моем примере как раз тест красный, так как в дз допущена ошибка

2021-09-24 09:08 UTC, zmd73 commented
Tested

2021-09-24 09:11 UTC, mrgreyves approved these changes
Здравствуйте!) Апрув!)

2021-09-24 09:18 UTC, zmd73 commented
merge DZ-2

2021-09-24 09:18 UTC, merged